module.exports = [
    {        
        name: "Eagle Rare",
        desc: "Aged for a minimum of ten years, this Kentucky straight bourbon was named the Best Bourbon at the 2013 International Wine and Spirits Competition and won a Gold Medal at the World Whisky Masters in 2017.Eagle Rare Kentucky Straight Bourbon Whiskey is.",        
        thumbnail: "https://cdn11.bigcommerce.com/s-7a906/images/stencil/1280x1280/products/1279/8691/Eagle_Rare_10__14110.1433435060.jpg?c=2&imbypass=on",
        category: 1,
        purchaseDate: "2020-05-15",
        purchaseLocation: "West Side Beverage",
        bottledDate: "",
        msrp: "$35 - $45",
        paid: "",
        tastingNotes: "The nose is complex, with aromas of toffee, hints of orange peel, herbs, honey, leather and oak. The taste is bold, dry and delicate with notes of candied almonds and very rich cocoa. The finish is dry and lingering.",
        brand: "Eagle Rare",
        volume: "100",
        rating: "7",
        distillery: "Buffalo Trace",
        barcode: "",
        age: "10"
    },
    {
        name: "Test 2",
        desc: "Description two",
        thumbnail: "https://www.liquor.com/thmb/bXvxHdDj3eHSnDPbE29cuMACeHw=/fit-in/960x1227/filters:no_upscale():max_bytes(150000):strip_icc()/MakersMark_CaskStrength_960x-2c94315ec87a40c98deeea493102b0e2.jpeg",
        category: "Kentucky",
        purchaseDate: "2021-06-13",
        purchaseLocation: "West Side Beverage",
        bottledDate: "",
        msrp: "",
        paid: "",
        tastingNotes: "",
        brand: "Kentucky 2",
        volume: "100",
        rating: "8",
        distillery: "",
        barcode: ""
    },
    {
        name: "Test 3",
        desc: "Description three",
        thumbnail: "https://www.liquor.com/thmb/cINc6uorfG4h4VFXeRP_4MWBYjg=/960x1227/filters:no_upscale():max_bytes(150000):strip_icc()/jack-daniel-tennesee-whiskey-889e9e5d0c94475a9119e966ebad7ff2.jpg",
        category: "Tennessee",
        purchaseDate: "2022-05-05",
        purchaseLocation: "West Side Beverage",
        bottledDate: "",
        msrp: "",
        paid: "",
        tastingNotes: "",
        brand: "Tennessee 3",
        volume: "100",
        rating: "6",
        distillery: "",
        barcode: ""
    },
    {
        name: "Test 4",
        desc: "Description four",
        thumbnail: "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h91/h81/15448919441438.png",
        category: "Straight",
        purchaseDate: "2022-06-20",
        purchaseLocation: "West Side Beverage",
        bottledDate: "",
        msrp: "",
        paid: "",
        tastingNotes: "",
        brand: "Straight 4",
        volume: "100",
        rating: "6.5",
        distillery: "",
        barcode: ""
    },
    {
        name: "Vodka 5",
        desc: "Description five",
        thumbnail: "https://www.absolut.com/globalassets/images/products/absolut-vodka/atlas/ingredient_absolut-vodka_1000ml_us_packshot.jpg",
        category: "Vodka",
        purchaseDate: "2022-08-20",
        purchaseLocation: "West Side Beverage",
        bottledDate: "",
        msrp: "",
        paid: "",
        tastingNotes: "",
        brand: "Vodka 5",
        volume: "100",
        rating: "3.5",
        distillery: "",
        barcode: ""
    }
];